import type { TabData } from '../types/insPlanBasic';

export const MOCK_DATA: Record<string, TabData> = {
  tab1: {
    id: '9425002',
    name: '홍길동',
    personalInfoPath: '본인',
    deliveryType: '1',
    deliveryAddress: '서울 은평구 통일로 88가길 10-26',
    deliveryDetailAddress: '101호',
    planType: '1',
    planOption: '1',
    deliveryTerm: '',
    deliveryOption: '',
    maturityTerm: '100',
    maturityOption: '',
    paymentCycle: '1',
    noticeType: '1',
    insured: [
      {
        name: '홍장동',
        gender: '남',
        age: '45',
        ageIncreaseDate: '',
        job: '회사원',
        lossDate: '2023-11-15',
        drivingType: '자가용',
        twoWheeled: '미가입',
        contractor: '본인',
        insured: '본인',
      },
    ],
    insuranceStartDate: '2023-11-15',
    insurancePeriod: ['2023-11-15', '2025-12-15'],
  },
  tab2: {
    id: '0894325',
    name: '김철수',
    personalInfoPath: '대리인',
    deliveryType: '2',
    deliveryAddress: '부산 중구 중앙대로 98번길 45',
    deliveryDetailAddress: '202호',
    planType: '1',
    planOption: '2',
    deliveryTerm: '15',
    deliveryOption: '2',
    maturityTerm: '100',
    maturityOption: '2',
    paymentCycle: '2',
    noticeType: '2',
    insured: [
      {
        name: '김영희',
        gender: '여',
        age: '38',
        ageIncreaseDate: '2024-03-15',
        job: '교사',
        lossDate: '2024-01-10',
        drivingType: '자가용',
        twoWheeled: '가입',
        contractor: '배우자',
        insured: '배우자',
      },
      {
        name: '김민준',
        gender: '남',
        age: '12',
        ageIncreaseDate: '2023-08-20',
        job: '학생',
        lossDate: '2023-06-05',
        drivingType: '미해당',
        twoWheeled: '미가입',
        contractor: '자녀',
        insured: '자녀',
      },
    ],
    insuranceStartDate: '2024-01-10',
    insurancePeriod: ['2024-01-10', '2039-01-10'],
  },
  tab3: {
    id: '0443555',
    name: '이영희',
    personalInfoPath: '본인',
    deliveryType: '1',
    deliveryAddress: '대구 중구 서성로 31길 65',
    deliveryDetailAddress: '303호',
    planType: '1',
    planOption: '1',
    deliveryTerm: '20',
    deliveryOption: '1',
    maturityTerm: '90',
    maturityOption: '1',
    paymentCycle: '1',
    noticeType: '3',
    insured: [
      {
        name: '이정호',
        gender: '남',
        age: '56',
        ageIncreaseDate: '2024-05-12',
        job: '회사원',
        lossDate: '2024-02-28',
        drivingType: '자가용',
        twoWheeled: '미가입',
        contractor: '배우자',
        insured: '배우자',
      },
    ],
    insuranceStartDate: '2024-02-28',
    insurancePeriod: ['2024-02-28', '2044-02-28'],
  },
  tab4: {
    id: '0547783',
    name: '박민수',
    personalInfoPath: '본인',
    deliveryType: '2',
    deliveryAddress: '인천 남동구 남부순환로 1123',
    deliveryDetailAddress: '404호',
    planType: '1',
    planOption: '2',
    deliveryTerm: '25',
    deliveryOption: '2',
    maturityTerm: '80',
    maturityOption: '2',
    paymentCycle: '2',
    noticeType: '4',
    insured: [
      {
        name: '박수진',
        gender: '여',
        age: '48',
        ageIncreaseDate: '2023-09-08',
        job: '의사',
        lossDate: '2023-07-22',
        drivingType: '자가용',
        twoWheeled: '미가입',
        contractor: '배우자',
        insured: '배우자',
      },
    ],
    insuranceStartDate: '2023-07-22',
    insurancePeriod: ['2023-07-22', '2048-07-22'],
  },
};

export type TabKey = keyof typeof MOCK_DATA;

export const INITIAL_TABS: Array<{ value: TabKey; label: string }> = [
  { value: 'tab1', label: '9425002' },
  { value: 'tab2', label: '0894325' },
  { value: 'tab3', label: '0443555' },
  { value: 'tab4', label: '0547783' },
];

export const SELECT_OPTIONS = {
  personalInfoPath: [
    { label: '본인', value: '본인' },
    { label: '대리인', value: '대리인' },
  ],
  deliveryType: [
    { label: '자택', value: '1' },
    { label: '회사', value: '2' },
  ],
  planOption: [
    { label: '기본플랜', value: '1' },
    { label: '간편플랜', value: '2' },
  ],
  deliveryTerm: [
    { label: '10년', value: '10' },
    { label: '15년', value: '15' },
    { label: '20년', value: '20' },
    { label: '25년', value: '25' },
    { label: '30년', value: '30' },
  ],
  gender: [
    { label: '남', value: '남' },
    { label: '여', value: '여' },
  ],
  drivingType: [
    { label: '자가용', value: '자가용' },
    { label: '영업용', value: '영업용' },
    { label: '미해당', value: '미해당' },
  ],
  twoWheeled: [
    { label: '가입', value: '가입' },
    { label: '미가입', value: '미가입' },
  ],
  relationship: [
    { label: '본인', value: '본인' },
    { label: '배우자', value: '배우자' },
    { label: '자녀', value: '자녀' },
    { label: '부모', value: '부모' },
  ],
  deliveryOptionData: [
    { label: '납기1', value: '1' },
    { label: '납기2', value: '2' },
  ],
  maturityOptionData: [
    { label: '만기1', value: '1' },
    { label: '만기2', value: '2' },
  ],
  paymentCycleData: [
    { label: '월납', value: '1' },
    { label: '연납', value: '2' },
  ],
};

export const RADIO_OPTIONS = {
  planSelect: [{ label: '기본플랜', value: '1' }],
  deliveryDate: [
    { label: '10년', value: '10', required: true },
    { label: '15년', value: '15', required: true },
    { label: '20년', value: '20', required: true },
    { label: '25년', value: '25', required: true },
    { label: '30년', value: '30', required: true },
  ],
  maturityAge: [
    { label: '110', value: '110' },
    { label: '100', value: '100' },
    { label: '90', value: '90' },
    { label: '80', value: '80' },
  ],
  noticeType: [
    { label: '1형(355간편고지형)', value: '1' },
    { label: '2형(345간편고지형)', value: '2' },
    { label: '3형(335간편고지형)', value: '3' },
    { label: '4형(325간편고지형)', value: '4' },
    { label: '5형(315간편고지형)', value: '5' },
    { label: '6형(305간편고지형)', value: '6' },
  ],
};
