// 공유 MOCK_DATA - 모든 상품 정보 (dep2, dep3 포함)
export const SHARED_MOCK_DATA = [
  {
    id: 1,
    selected: false,
    category: '종합건강',
    age: '25~59세',
    productName: '한화 시그니처 여성 건강보험3.0 2504',
    underwritingType: '할증',
    noSurrender: true,
    favorite: true,
    notification: true,
    isHighlighted: false,
    dep2: [
      {
        type: '1종',
        name: '납입후50%해약환급금지급형, 간편고지형',
        id: 'pymXmp0',
        dep3: [
          { plan: '회사플랜', name: '올인원플랜(10~40세)' },
          { plan: '회사플랜', name: '올인원플랜(10~40세)' },
          { plan: '기관플랜', name: '올인원플랜(10~40세)' },
          { plan: '모집자플랜', name: '올인원플랜(10~40세)' },
        ],
      },
      {
        type: '2종',
        name: '기본형, 간편고지형',
        id: 'pymXmp1',
        dep3: [{ plan: '기관플랜', name: '올인원플랜(10~40세)' }],
      },
      {
        type: '3종',
        name: '납입후50%해약환급금지급형, 일반고지형',
        id: 'pymXmp2',
        dep3: [{ plan: '회사플랜', name: '올인원플랜(10~40세)' }],
      },
      {
        type: '4종',
        name: '기본형, 일반고지형',
        id: 'pymXmp3',
        dep3: [{ plan: '모집자플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 2,
    selected: false,
    category: '종합건강',
    age: '15~24세',
    productName: '한화 더 건강한 한아름종합보험 2504',
    underwritingType: '할증',
    noSurrender: true,
    favorite: false,
    notification: true,
    isHighlighted: true,
    dep2: [
      {
        type: '1종',
        name: '납입후50%해약환급금지급형, 간편고지형',
        id: 'pymXmp0',
        dep3: [{ plan: '회사플랜', name: '올인원플랜(10~40세)' }],
      },
      {
        type: '2종',
        name: '기본형, 간편고지형',
        id: 'pymXmp1',
        dep3: [{ plan: '기관플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 3,
    selected: false,
    category: '암보험',
    age: '0~14세',
    productName: '한화 더 경증 간편건강보험 II(세만기형)',
    underwritingType: '간편',
    noSurrender: true,
    favorite: false,
    notification: false,
    isHighlighted: false,
    dep2: [
      {
        type: '2종',
        name: '기본형, 간편고지형',
        id: 'pymXmp1',
        dep3: [{ plan: '기관플랜', name: '올인원플랜(10~40세)' }],
      },
      {
        type: '4종',
        name: '기본형, 일반고지형',
        id: 'pymXmp3',
        dep3: [{ plan: '모집자플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 4,
    selected: false,
    category: '암보험',
    age: '60~65세',
    productName: '한화 더 경증 간편건강보험(연만기 갱신형) 2504',
    underwritingType: '간편',
    noSurrender: false,
    favorite: true,
    notification: true,
    isHighlighted: true,
    dep2: [{ type: '1종', name: '납입후50%해약환급금지급형, 간편고지형', id: 'pymXmp0', dep3: [] }],
  },
  {
    id: 5,
    selected: false,
    category: '실손보험',
    age: '25~59세',
    productName: '한화 3N5 더간편건강보험(세만기형)',
    underwritingType: '간편',
    noSurrender: true,
    favorite: false,
    notification: false,
    isHighlighted: false,
    dep2: [
      {
        type: '3종',
        name: '납입후50%해약환급금지급형, 일반고지형',
        id: 'pymXmp2',
        dep3: [{ plan: '회사플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 6,
    selected: false,
    category: '실손보험',
    age: '60~65세',
    productName: '한화 3N5 더간편건강보험(연만기 갱신형)',
    underwritingType: '간편',
    noSurrender: false,
    favorite: false,
    notification: true,
    isHighlighted: false,
    dep2: [
      {
        type: '1종',
        name: '납입후50%해약환급금지급형, 간편고지형',
        id: 'pymXmp0',
        dep3: [{ plan: '기관플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 7,
    selected: false,
    category: '간편',
    age: '66세 이상',
    productName: '한화 시그니처 여성 3N5간편건강보험3.0 2504',
    underwritingType: '간편',
    noSurrender: true,
    favorite: false,
    notification: false,
    isHighlighted: false,
    dep2: [
      {
        type: '4종',
        name: '기본형, 일반고지형',
        id: 'pymXmp3',
        dep3: [{ plan: '모집자플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 8,
    selected: false,
    category: '암보험',
    age: '15~24세',
    productName: '한화 시그니처 여성 355간편건강보험(세만기형)3.0 2504',
    underwritingType: '간편',
    noSurrender: false,
    favorite: true,
    notification: false,
    isHighlighted: false,
    dep2: [
      {
        type: '1종',
        name: '납입후50%해약환급금지급형, 간편고지형',
        id: 'pymXmp0',
        dep3: [{ plan: '회사플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 9,
    selected: false,
    category: '암보험',
    age: '25~59세',
    productName: '한화 시그니처 여성 355간편건강보험(연만기 갱신형)3.0 2504',
    underwritingType: '간편',
    noSurrender: false,
    favorite: true,
    notification: false,
    isHighlighted: false,
    dep2: [
      {
        type: '2종',
        name: '기본형, 간편고지형',
        id: 'pymXmp1',
        dep3: [{ plan: '기관플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 10,
    selected: false,
    category: '의료비',
    age: '0~14세',
    productName: '한화 311 간편건강보험(연만기 갱신형)',
    underwritingType: '할증',
    noSurrender: false,
    favorite: false,
    notification: true,
    isHighlighted: false,
    dep2: [{ type: '1종', name: '납입후50%해약환급금지급형, 간편고지형', id: 'pymXmp0', dep3: [] }],
  },
  {
    id: 11,
    selected: false,
    category: '종합건강',
    age: '60~65세',
    productName: '한화 시그니처 여성 건강보험3.0 2504',
    underwritingType: '할증',
    noSurrender: true,
    favorite: false,
    notification: false,
    isHighlighted: false,
    dep2: [
      {
        type: '2종',
        name: '기본형, 간편고지형',
        id: 'pymXmp1',
        dep3: [{ plan: '회사플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 12,
    selected: false,
    category: '재물',
    age: '66세 이상',
    productName: '한화 더 건강 치아보험 2504',
    underwritingType: '할증',
    noSurrender: true,
    favorite: false,
    notification: true,
    isHighlighted: false,
    dep2: [{ type: '3종', name: '납입후50%해약환급금지급형, 일반고지형', id: 'pymXmp2', dep3: [] }],
  },
  {
    id: 13,
    selected: false,
    category: '상해',
    age: '25~59세',
    productName: '한화 시그니처 상해보험 2504',
    underwritingType: '간편',
    noSurrender: true,
    favorite: true,
    notification: false,
    isHighlighted: false,
    dep2: [
      {
        type: '1종',
        name: '납입후50%해약환급금지급형, 간편고지형',
        id: 'pymXmp0',
        dep3: [{ plan: '기관플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 14,
    selected: false,
    category: '연금/저축',
    age: '66세 이상',
    productName: '한화 더 든든한 연금저축 2504',
    underwritingType: null,
    noSurrender: false,
    favorite: false,
    notification: true,
    isHighlighted: false,
    dep2: [
      {
        type: '4종',
        name: '기본형, 일반고지형',
        id: 'pymXmp3',
        dep3: [{ plan: '회사플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 15,
    selected: false,
    category: '자녀/치아',
    age: '0~14세',
    productName: '한화 자녀보험 플러스 2504',
    underwritingType: '간편',
    noSurrender: true,
    favorite: false,
    notification: false,
    isHighlighted: false,
    dep2: [{ type: '2종', name: '기본형, 간편고지형', id: 'pymXmp1', dep3: [] }],
  },
  {
    id: 16,
    selected: false,
    category: '종합건강',
    age: '60~65세',
    productName: '한화 직장인 건강보험 2504',
    underwritingType: '할증',
    noSurrender: true,
    favorite: true,
    notification: true,
    isHighlighted: false,
    dep2: [
      {
        type: '1종',
        name: '납입후50%해약환급금지급형, 간편고지형',
        id: 'pymXmp0',
        dep3: [{ plan: '모집자플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 17,
    selected: false,
    category: '의료비',
    age: '25~59세',
    productName: '한화 가족의료비 보장 2504',
    underwritingType: '간편',
    noSurrender: false,
    favorite: false,
    notification: false,
    isHighlighted: true,
    dep2: [
      {
        type: '3종',
        name: '납입후50%해약환급금지급형, 일반고지형',
        id: 'pymXmp2',
        dep3: [{ plan: '회사플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 18,
    selected: false,
    category: '암/간병',
    age: '66세 이상',
    productName: '한화 암 진단 보장 보험 2504',
    underwritingType: '할증',
    noSurrender: true,
    favorite: false,
    notification: true,
    isHighlighted: false,
    dep2: [
      {
        type: '1종',
        name: '납입후50%해약환급금지급형, 간편고지형',
        id: 'pymXmp0',
        dep3: [{ plan: '기관플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
  {
    id: 19,
    selected: false,
    category: '간편',
    age: '15~24세',
    productName: '한화 간편 가입 건강보험 2504',
    underwritingType: '간편',
    noSurrender: true,
    favorite: true,
    notification: false,
    isHighlighted: false,
    dep2: [{ type: '2종', name: '기본형, 간편고지형', id: 'pymXmp1', dep3: [] }],
  },
  {
    id: 20,
    selected: false,
    category: '실손보험',
    age: '25~59세',
    productName: '한화 실손의료 멀티플랜 2504',
    underwritingType: '할증',
    noSurrender: false,
    favorite: false,
    notification: true,
    isHighlighted: false,
    dep2: [
      {
        type: '4종',
        name: '기본형, 일반고지형',
        id: 'pymXmp3',
        dep3: [{ plan: '모집자플랜', name: '올인원플랜(10~40세)' }],
      },
    ],
  },
];
