
// TestData 타입 정의
export interface TestDataType {
  data: Array<{
    id: number;
    locked?: boolean; // 잠금 여부 추가
    isDuplicate: boolean;
    productName: string;
    coverageAmount: number;
    attribute: boolean;
    premium: number;
    availableAmount: number;
    expiryPeriod: string;
    paymentPeriod: string;
    expectedUwResult: string;
    isHighlighted: boolean;
    canEditExpiry: boolean;
    selected?: boolean;
    badge?: string[]; 
  }>;
}
export const TestData: TestDataType = {
  data: [
    {
      id: 1,
      locked: true,
      isDuplicate: true,
      productName: '무배당 삼성화재 실손의료보험 무배당 삼성화재 실손의료보험',
      coverageAmount: 500,
      attribute: true,
      premium: 450,
      availableAmount: 100,
      expiryPeriod: '80세',
      paymentPeriod: '20년',
      expectedUwResult: '인수',
      isHighlighted: true,
      canEditExpiry: true, 
      badge: ['독립', '갱신'],
    },
    {
      id: 2,
      locked: true,
      isDuplicate: true,
      productName: '무배당 메리츠 종합보험 무배당 메리츠 종합보험무배당 메리츠 종합보험무배당 메리츠 종합보험',
      coverageAmount: 300,
      attribute: false,
      premium: 350,
      availableAmount: 500,
      expiryPeriod: '100세',
      paymentPeriod: '전기납',
      expectedUwResult: '조건부인수',
      isHighlighted: false,
      canEditExpiry: false,
    },
    {
      id: 3,
      locked: false,
      isDuplicate: true,
      productName: 'KB손해보험 암보험KB손해보험 암보험KB손해보험 암보험KB손해보험 암보험',
      coverageAmount: 700,
      attribute: false,
      premium: 550,
      availableAmount: 1500,
      expiryPeriod: '90세',
      paymentPeriod: '15년',
      expectedUwResult: '인수',
      isHighlighted: false,
      canEditExpiry: true,
      badge: ['독립'],
    },
    {
      id: 4,
      locked: false,
      isDuplicate: true,
      productName: '한화생명 의료실비보험',
      coverageAmount: 450,
      attribute: false,
      premium: 420,
      availableAmount: 900,
      expiryPeriod: '85세',
      paymentPeriod: '10년',
      expectedUwResult: '거절',
      isHighlighted: false,
      canEditExpiry: false,
      badge: ['갱신'],
    },
    {
      id: 5,
      locked: false,
      isDuplicate: true,
      productName: '롯데생명 종신보험',
      coverageAmount: 100,
      attribute: false,
      premium: 750,
      availableAmount: 200,
      expiryPeriod: '100세',
      paymentPeriod: '전기납',
      expectedUwResult: '조건부인수',
      isHighlighted: false,
      canEditExpiry: true,
    },
    {
      id: 6,
      locked: false,
      isDuplicate: true,
      productName: '현대생명 정기보험',
      coverageAmount: 600,
      attribute: false,
      premium: 480,
      availableAmount: 1200,
      expiryPeriod: '80세',
      paymentPeriod: '20년',
      expectedUwResult: '인수',
      isHighlighted: false,
      canEditExpiry: false,
    },
    {
      id: 7,
      locked: false,
      isDuplicate: true,
      productName: 'AXA손해보험 질병보험',
      coverageAmount: 550,
      attribute: false,
      premium: 500,
      availableAmount: 1100,
      expiryPeriod: '75세',
      paymentPeriod: '15년',
      expectedUwResult: '조건부인수',
      isHighlighted: false,
      canEditExpiry: true,
    },
    {
      id: 8,
      locked: false,
      isDuplicate: true,
      productName: '삼성생명 어린이보험',
      coverageAmount: 250,
      attribute: false,
      premium: 280,
      availableAmount: 400,
      expiryPeriod: '30세',
      paymentPeriod: '15년',
      expectedUwResult: '인수',
      isHighlighted: false,
      canEditExpiry: false,
    },
    {
      id: 9,
      locked: false,
      isDuplicate: true,
      productName: '교보생명 장기요양보험',
      coverageAmount: 800,
      attribute: false,
      premium: 650,
      availableAmount: 1600,
      expiryPeriod: '100세',
      paymentPeriod: '20년',
      expectedUwResult: '인수',
      isHighlighted: false,
      canEditExpiry: true,
    },
    {
      id: 10,
      locked: false,
      isDuplicate: true,
      productName: '신한생명 변액보험',
      coverageAmount: 900,
      attribute: true,
      premium: 700,
      availableAmount: 1800,
      expiryPeriod: '80세',
      paymentPeriod: '15년',
      expectedUwResult: '거절',
      isHighlighted: false,
      canEditExpiry: false,
    },
    {
      id: 11,
      locked: false,
      isDuplicate: true,
      productName: 'DB손해보험 특정질병보험',
      coverageAmount: 350,
      attribute: true,
      premium: 380,
      availableAmount: 700,
      expiryPeriod: '65세',
      paymentPeriod: '10년',
      expectedUwResult: '조건부인수',
      isHighlighted: false,
      canEditExpiry: true,
    },
    {
      id: 12,
      locked: false,
      isDuplicate: true,
      productName: '우리생명 연금보험',
      coverageAmount: 1200,
      attribute: true,
      premium: 850,
      availableAmount: 2500,
      expiryPeriod: '100세',
      paymentPeriod: '전기납',
      expectedUwResult: '인수',
      isHighlighted: false,
      canEditExpiry: false,
    },
    {
      id: 13,
      locked: false,
      isDuplicate: true,
      productName: '동부화재 운전자보험',
      coverageAmount: 400,
      attribute: true,
      premium: 320,
      availableAmount: 800,
      expiryPeriod: '75세',
      paymentPeriod: '20년',
      expectedUwResult: '인수',
      isHighlighted: false,
      canEditExpiry: true,
    },
    {
      id: 14,
      locked: false,
      isDuplicate: true,
      productName: '미래에셋생명 저축보험',
      coverageAmount: 750,
      attribute: true,
      premium: 600,
      availableAmount: 1500,
      expiryPeriod: '85세',
      paymentPeriod: '15년',
      expectedUwResult: '거절',
      isHighlighted: false,
      canEditExpiry: false,
    },
    {
      id: 15,
      locked: false,
      isDuplicate: true,
      productName: '하나생명 여행보험',
      coverageAmount: 200,
      attribute: true,
      premium: 250,
      availableAmount: 300,
      expiryPeriod: '80세',
      paymentPeriod: '10년',
      expectedUwResult: '인수',
      isHighlighted: false,
      canEditExpiry: true,
    },
  ],
}


