'use client';

import { useState } from 'react';
import { InsPlanBasic, InsPlanCov } from '../components/Page3Index';
import { INITIAL_TABS2 } from '../constants/insPlanBasicData';
import { Tabs, TabsList, TabsContent, TabsTrigger } from '@/shared/components/uiux';
import { useTabs } from '@/shared/hooks/useTabs';

// 테스트용 더미 데이터
const DUMMY_PLAN_COV_DATA = [
  {
    id: 1,
    isDuplicate: false,
    productName: '무배당 삼성화재 실손의료보험',
    coverageAmount: 50000000,
    premium: 45000,
    availableAmount: 100000000,
    expiryPeriod: '80세',
    paymentPeriod: '20년',
    expectedUwResult: '인수',
    isHighlighted: true,
  },
  {
    id: 2,
    isDuplicate: true,
    productName: '무배당 메리츠 종합보험',
    coverageAmount: 30000000,
    premium: 35000,
    availableAmount: 50000000,
    expiryPeriod: '100세',
    paymentPeriod: '전기납',
    expectedUwResult: '조건부인수',
    isHighlighted: false,
  },
  {
    id: 3,
    isDuplicate: false,
    productName: 'KB손해보험 암보험',
    coverageAmount: 70000000,
    premium: 55000,
    availableAmount: 150000000,
    expiryPeriod: '90세',
    paymentPeriod: '15년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 4,
    isDuplicate: false,
    productName: '한화생명 의료실비보험',
    coverageAmount: 45000000,
    premium: 42000,
    availableAmount: 90000000,
    expiryPeriod: '85세',
    paymentPeriod: '10년',
    expectedUwResult: '거절',
    isHighlighted: false,
  },
  {
    id: 5,
    isDuplicate: true,
    productName: '롯데생명 종신보험',
    coverageAmount: 100000000,
    premium: 75000,
    availableAmount: 200000000,
    expiryPeriod: '100세',
    paymentPeriod: '전기납',
    expectedUwResult: '조건부인수',
    isHighlighted: false,
  },
  {
    id: 6,
    isDuplicate: false,
    productName: '현대생명 정기보험',
    coverageAmount: 60000000,
    premium: 48000,
    availableAmount: 120000000,
    expiryPeriod: '80세',
    paymentPeriod: '20년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 7,
    isDuplicate: false,
    productName: 'AXA손해보험 질병보험',
    coverageAmount: 55000000,
    premium: 50000,
    availableAmount: 110000000,
    expiryPeriod: '75세',
    paymentPeriod: '15년',
    expectedUwResult: '조건부인수',
    isHighlighted: false,
  },
  {
    id: 8,
    isDuplicate: true,
    productName: '삼성생명 어린이보험',
    coverageAmount: 25000000,
    premium: 28000,
    availableAmount: 40000000,
    expiryPeriod: '30세',
    paymentPeriod: '12년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 9,
    isDuplicate: false,
    productName: '교보생명 장기요양보험',
    coverageAmount: 80000000,
    premium: 65000,
    availableAmount: 160000000,
    expiryPeriod: '100세',
    paymentPeriod: '20년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 10,
    isDuplicate: false,
    productName: '신한생명 변액보험',
    coverageAmount: 90000000,
    premium: 70000,
    availableAmount: 180000000,
    expiryPeriod: '80세',
    paymentPeriod: '15년',
    expectedUwResult: '거절',
    isHighlighted: false,
  },
  {
    id: 11,
    isDuplicate: true,
    productName: 'DB손해보험 특정질병보험',
    coverageAmount: 35000000,
    premium: 38000,
    availableAmount: 70000000,
    expiryPeriod: '65세',
    paymentPeriod: '10년',
    expectedUwResult: '조건부인수',
    isHighlighted: false,
  },
  {
    id: 12,
    isDuplicate: false,
    productName: '우리생명 연금보험',
    coverageAmount: 120000000,
    premium: 85000,
    availableAmount: 250000000,
    expiryPeriod: '100세',
    paymentPeriod: '전기납',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 13,
    isDuplicate: false,
    productName: '동부화재 운전자보험',
    coverageAmount: 40000000,
    premium: 32000,
    availableAmount: 80000000,
    expiryPeriod: '75세',
    paymentPeriod: '20년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 14,
    isDuplicate: true,
    productName: '미래에셋생명 저축보험',
    coverageAmount: 75000000,
    premium: 60000,
    availableAmount: 150000000,
    expiryPeriod: '85세',
    paymentPeriod: '15년',
    expectedUwResult: '거절',
    isHighlighted: false,
  },
  {
    id: 15,
    isDuplicate: false,
    productName: '하나생명 여행보험',
    coverageAmount: 20000000,
    premium: 25000,
    availableAmount: 30000000,
    expiryPeriod: '80세',
    paymentPeriod: '1년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 16,
    isDuplicate: false,
    productName: 'DL손해보험 주택보험',
    coverageAmount: 150000000,
    premium: 95000,
    availableAmount: 300000000,
    expiryPeriod: '무제한',
    paymentPeriod: '1년',
    expectedUwResult: '조건부인수',
    isHighlighted: false,
  },
  {
    id: 17,
    isDuplicate: true,
    productName: '별코 종신보험',
    coverageAmount: 65000000,
    premium: 52000,
    availableAmount: 130000000,
    expiryPeriod: '90세',
    paymentPeriod: '20년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 18,
    isDuplicate: false,
    productName: '태연생명 치과보험',
    coverageAmount: 15000000,
    premium: 18000,
    availableAmount: 25000000,
    expiryPeriod: '80세',
    paymentPeriod: '10년',
    expectedUwResult: '거절',
    isHighlighted: false,
  },
  {
    id: 19,
    isDuplicate: false,
    productName: '경남정보통신 보장성보험',
    coverageAmount: 85000000,
    premium: 68000,
    availableAmount: 170000000,
    expiryPeriod: '85세',
    paymentPeriod: '20년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 20,
    isDuplicate: true,
    productName: '한국신용정보 생활보험',
    coverageAmount: 50000000,
    premium: 45000,
    availableAmount: 100000000,
    expiryPeriod: '80세',
    paymentPeriod: '15년',
    expectedUwResult: '조건부인수',
    isHighlighted: false,
  },
  {
    id: 21,
    isDuplicate: false,
    productName: '푸른보험 휴직보험',
    coverageAmount: 30000000,
    premium: 32000,
    availableAmount: 60000000,
    expiryPeriod: '60세',
    paymentPeriod: '10년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 22,
    isDuplicate: false,
    productName: '한화손해보험 배상책임보험',
    coverageAmount: 100000000,
    premium: 78000,
    availableAmount: 200000000,
    expiryPeriod: '무제한',
    paymentPeriod: '1년',
    expectedUwResult: '거절',
    isHighlighted: false,
  },
  {
    id: 23,
    isDuplicate: true,
    productName: '롯데손해보험 펫보험',
    coverageAmount: 10000000,
    premium: 15000,
    availableAmount: 20000000,
    expiryPeriod: '10세',
    paymentPeriod: '1년',
    expectedUwResult: '조건부인수',
    isHighlighted: false,
  },
  {
    id: 24,
    isDuplicate: false,
    productName: '삼성화재 골프보험',
    coverageAmount: 50000000,
    premium: 48000,
    availableAmount: 100000000,
    expiryPeriod: '80세',
    paymentPeriod: '1년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 25,
    isDuplicate: false,
    productName: '현대해상 해외여행보험',
    coverageAmount: 25000000,
    premium: 28000,
    availableAmount: 50000000,
    expiryPeriod: '80세',
    paymentPeriod: '1년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 26,
    isDuplicate: true,
    productName: 'AIG손해보험 기업배상보험',
    coverageAmount: 200000000,
    premium: 120000,
    availableAmount: 400000000,
    expiryPeriod: '무제한',
    paymentPeriod: '1년',
    expectedUwResult: '조건부인수',
    isHighlighted: false,
  },
  {
    id: 27,
    isDuplicate: false,
    productName: '메트라이프 장기간병보험',
    coverageAmount: 110000000,
    premium: 82000,
    availableAmount: 220000000,
    expiryPeriod: '100세',
    paymentPeriod: '20년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
  {
    id: 28,
    isDuplicate: false,
    productName: '한국지역난방공사 보장성보험',
    coverageAmount: 55000000,
    premium: 50000,
    availableAmount: 110000000,
    expiryPeriod: '80세',
    paymentPeriod: '20년',
    expectedUwResult: '거절',
    isHighlighted: false,
  },
  {
    id: 29,
    isDuplicate: true,
    productName: '케이 생명 암보험',
    coverageAmount: 70000000,
    premium: 58000,
    availableAmount: 140000000,
    expiryPeriod: '90세',
    paymentPeriod: '20년',
    expectedUwResult: '조건부인수',
    isHighlighted: false,
  },
  {
    id: 30,
    isDuplicate: false,
    productName: '보장보험 건강증진보험',
    coverageAmount: 65000000,
    premium: 54000,
    availableAmount: 130000000,
    expiryPeriod: '85세',
    paymentPeriod: '15년',
    expectedUwResult: '인수',
    isHighlighted: false,
  },
];

export default function Main() {
  const { active, setActive, handleRemove, visibleTabs } = useTabs(INITIAL_TABS2);
  const [selectedPlanId, setSelectedPlanId] = useState<number | null>(null);

  const handleSelectPlan = (planId: number) => {
    setSelectedPlanId(planId);
  };

  return (
    <div className="flex flex-col w-full h-full gap-6 resizablePanel-line">
      <Tabs value={active} onValueChange={setActive} className="w-full h-full grid grid-rows-[auto_1fr] content-start">
        <div className="border-b border-[#FF5C2E]">
          <TabsList>
            {visibleTabs.map((tab) => (
              <TabsTrigger key={tab.value} value={tab.value} removable onRemove={() => handleRemove(tab.value)}>
                {tab.label}
              </TabsTrigger>
            ))}
          </TabsList>
        </div>
        <TabsContent value={active}>
          <div className="grid grid-rows-[auto_1fr] gap-[2rem]">
            <InsPlanBasic />
            <InsPlanCov data={DUMMY_PLAN_COV_DATA} selectedPlanId={selectedPlanId} onSelectPlan={handleSelectPlan} />
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
